# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierIntegration',
            fields=[
                ('carrier_id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('tracking_url', models.CharField(max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(max_length=255)),
                ('estimated_delivery_date', models.DateTimeField()),
                ('real_time_tracking_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySignatures',
            fields=[
                ('signature_id', models.AutoField(primary_key=True, serialize=False)),
                ('signature_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRoutes',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_details', models.JSONField()),
                ('map_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNotifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryIssues',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_details', models.TextField()),
                ('event_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('pod_id', models.AutoField(primary_key=True, serialize=False)),
                ('pod_details', models.TextField()),
                ('pod_file_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_update', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('additional_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTracking.ordertracking')),
            ],
        ),
    ]
