# Generated by Django 5.0.6 on 2024-07-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartManagement', '0001_initial'),
        ('ProductManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CartDiscounts',
        ),
        migrations.RemoveField(
            model_name='cartexpiration',
            name='cart_id',
        ),
        migrations.DeleteModel(
            name='CartItemCustomization',
        ),
        migrations.DeleteModel(
            name='CartItemDetails',
        ),
        migrations.DeleteModel(
            name='CartItemNotes',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.DeleteModel(
            name='CartItemSubscription',
        ),
        migrations.RemoveField(
            model_name='cartpersistence',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CartPromotions',
        ),
        migrations.DeleteModel(
            name='CartRecommendations',
        ),
        migrations.DeleteModel(
            name='CartRecovery',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cartsaveforlater',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartsaveforlater',
            name='save_for_later_id',
        ),
        migrations.RemoveField(
            model_name='cartsaveforlater',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cartsharing',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cartsharing',
            name='share_id',
        ),
        migrations.RemoveField(
            model_name='cartsharing',
            name='shared_with_user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsaveforlater',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsaveforlater',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductManagement.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsaveforlater',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsharing',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CartManagement.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsharing',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartsharing',
            name='shared_with_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartdiscount',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartManagement.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartManagement.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManagement.product'),
        ),
        migrations.DeleteModel(
            name='CartExpiration',
        ),
        migrations.DeleteModel(
            name='CartPersistence',
        ),
    ]
