# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerManagement', '0001_initial'),
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateways',
            fields=[
                ('gateway_id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(max_length=255)),
                ('configuration', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('fraud_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('fraud_score', models.IntegerField()),
                ('fraud_alert', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_type', models.CharField(max_length=255)),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentProcessing.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('event_details', models.JSONField()),
                ('event_date', models.DateTimeField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentProcessing.payments')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTokens',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_type', models.CharField(max_length=255)),
                ('token_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPayments',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='SecureAuthentication',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentProcessing.paymentgateways')),
            ],
        ),
    ]
