# Generated by Django 5.0.6 on 2024-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionABTesting',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_description', models.TextField()),
                ('test_settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAnalytics',
            fields=[
                ('analytics_id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversions', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('roi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analytics_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAutomation',
            fields=[
                ('automation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('automation_name', models.CharField(max_length=255)),
                ('automation_type', models.CharField(max_length=255)),
                ('automation_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCollaborationHistory',
            fields=[
                ('collaboration_id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionContent',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('content_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCoupons',
            fields=[
                ('coupon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=255)),
                ('discount_type', models.CharField(max_length=255)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField()),
                ('uses_counter', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionIntegrations',
            fields=[
                ('integration_id', models.IntegerField(primary_key=True, serialize=False)),
                ('integration_name', models.CharField(max_length=255)),
                ('integration_details', models.JSONField()),
                ('enabled', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionPersonalization',
            fields=[
                ('personalization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField()),
                ('personalization_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRules',
            fields=[
                ('rule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_description', models.TextField()),
                ('conditions', models.JSONField()),
                ('actions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionSegments',
            fields=[
                ('segment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=255)),
                ('segment_criteria', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionTargeting',
            fields=[
                ('targeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=255)),
                ('target_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
