# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy_setting', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistSync',
            fields=[
                ('sync_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('devices', models.JSONField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistBackupRestore',
            fields=[
                ('backup_restore_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistCollaborator',
            fields=[
                ('collaboration_id', models.AutoField(primary_key=True, serialize=False)),
                ('collaborator_id', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistImportExport',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlistitem')),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('subscribed', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistPrivacy',
            fields=[
                ('privacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlistitem')),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendations', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlistitem')),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('settings', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistSharing',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_with', models.CharField(max_length=255)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistManagement.wishlist')),
            ],
        ),
    ]
