# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('carrier_id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('carrier_details', models.JSONField()),
                ('settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('preference_name', models.CharField(max_length=255)),
                ('preference_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRestriction',
            fields=[
                ('restriction_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShippingAndFulfillment.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='PackageTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('tracking_updates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShippingAndFulfillment.shippingcarrier')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimation_method', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInsurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_type', models.CharField(max_length=255)),
                ('label_url', models.CharField(max_length=255)),
                ('customization_settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.order')),
                ('restriction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShippingAndFulfillment.shippingrestriction')),
            ],
        ),
    ]
