# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValues',
            fields=[
                ('value_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute_id', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('indexed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchRelevanceRanking',
            fields=[
                ('ranking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('ranking_settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedSearchHistory',
            fields=[
                ('search_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('search_query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearches',
            fields=[
                ('saved_search_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('search_query', models.CharField(max_length=255)),
                ('saved_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFiltersPersistence',
            fields=[
                ('persistence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('filter_settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('search_query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultsExportHistory',
            fields=[
                ('export_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=255)),
                ('export_query', models.CharField(max_length=255)),
                ('exported_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
