# Generated by Django 5.0.6 on 2024-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRateOptimizationAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('conversion_funnel', models.JSONField()),
                ('ab_testing_results', models.JSONField()),
                ('landing_page_performance', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBehaviorAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_acquisition', models.IntegerField()),
                ('customer_retention', models.IntegerField()),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_segments', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerServiceAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('support_tickets', models.IntegerField()),
                ('feedback_sentiment', models.JSONField()),
                ('satisfaction_scores', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomReporting',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('report_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataVisualizationDashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=255)),
                ('dashboard_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReporting',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=255)),
                ('report_details', models.JSONField()),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManagementAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_levels', models.JSONField()),
                ('inventory_valuation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaignAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('campaign_performance', models.JSONField()),
                ('channel_effectiveness', models.JSONField()),
                ('marketing_roi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFulfillmentAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fulfillment_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_accuracy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_costs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPerformanceAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product_views', models.IntegerField()),
                ('product_purchases', models.IntegerField()),
                ('product_feedback', models.JSONField()),
                ('product_recommendations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_channels', models.JSONField()),
                ('sales_by_region', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagementAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user_activity', models.JSONField()),
                ('user_retention', models.DecimalField(decimal_places=2, max_digits=10)),
                ('churn_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
