# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAggregation',
            fields=[
                ('aggregation_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(max_length=255)),
                ('trends', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFilter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=255)),
                ('sort_order', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewGamification',
            fields=[
                ('gamification_id', models.AutoField(primary_key=True, serialize=False)),
                ('settings', models.JSONField()),
                ('leaderboard', models.JSONField()),
                ('rewards', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImportExport',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewIntegration',
            fields=[
                ('integration_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=255)),
                ('details', models.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponseTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('template_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('sentiment', models.CharField(max_length=255)),
                ('trend', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewsAndRatings.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAuthentication',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_token', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewsAndRatings.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewsAndRatings.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewsAndRatings.review')),
            ],
        ),
    ]
