# Generated by Django 5.0.6 on 2024-07-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_remove_video_product_media_delete_image_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
