# Generated by Django 5.0.6 on 2024-07-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0005_brand_user_category_user_discount_user_media_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='user',
        ),
    ]
